"""add normalized_class column to sample_unit

Revision ID: c899823f3b27
Revises: 3463b67b5a39
Create Date: 2026-06-25 21:21:36.422276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c899823f3b27'
down_revision: Union[str, Sequence[str], None] = '3463b67b5a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_results', sa.Column('normalized_class', sa.String(), nullable=True))
    op.add_column('sample_units', sa.Column('normalized_class', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_units', 'normalized_class')
    op.drop_column('detection_results', 'normalized_class')
    # ### end Alembic commands ###
