"""add images table, remove image string cols from sample_unit

Revision ID: 519e44e3777a
Revises: fe2d14e6f96f
Create Date: 2026-06-27 21:02:49.342490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519e44e3777a'
down_revision: Union[str, Sequence[str], None] = 'fe2d14e6f96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_units', 'predicted_image')
    op.drop_column('sample_units', 'is_random')
    op.drop_column('sample_units', 'original_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_units', sa.Column('original_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sample_units', sa.Column('is_random', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sample_units', sa.Column('predicted_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
