"""replace r2 image fields with cloudinary fields

Revision ID: 245aaa0525ac
Revises: 519e44e3777a
Create Date: 2026-06-28 22:59:42.546348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245aaa0525ac'
down_revision: Union[str, Sequence[str], None] = '519e44e3777a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
