"""add inference_status to sample_unit

Revision ID: fe2d14e6f96f
Revises: d2b89014e79a
Create Date: 2026-06-27 14:13:25.721353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2d14e6f96f'
down_revision: Union[str, Sequence[str], None] = 'd2b89014e79a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_units', sa.Column('inference_status', sa.String(), server_default='pending', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_units', 'inference_status')
    # ### end Alembic commands ###
