"""update pci and detectionResult tables

Revision ID: d2b89014e79a
Revises: c899823f3b27
Create Date: 2026-06-27 09:50:41.703067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b89014e79a'
down_revision: Union[str, Sequence[str], None] = 'c899823f3b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detection_results', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('pci_history', sa.Column('condition_rating', sa.String(), nullable=False))
    op.add_column('pci_history', sa.Column('max_cdv', sa.Float(), nullable=False))
    op.add_column('pci_history', sa.Column('tdv_start', sa.Float(), nullable=False))
    op.add_column('pci_history', sa.Column('observations', sa.JSON(), nullable=False))
    op.add_column('pci_history', sa.Column('all_cdvs', sa.JSON(), nullable=False))
    op.add_column('pci_history', sa.Column('all_tdvs', sa.JSON(), nullable=False))
    op.drop_column('pci_history', 'cdv')
    op.drop_column('pci_history', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pci_history', sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pci_history', sa.Column('cdv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('pci_history', 'all_tdvs')
    op.drop_column('pci_history', 'all_cdvs')
    op.drop_column('pci_history', 'observations')
    op.drop_column('pci_history', 'tdv_start')
    op.drop_column('pci_history', 'max_cdv')
    op.drop_column('pci_history', 'condition_rating')
    op.alter_column('detection_results', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
